name: Continuous Deployment

on:
    push:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Deploy cloud functions
              uses: lowply/deploy-firebase@v0.0.5
              with:
                  dir: functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
